#Set a gun to true to disable it and prevent its blueprint from appearing in loot tables.
[guns]
	"Disable Repair Tool" = false
	"Disable Taser" = true
	"Disable Glock 17" = true
	"Disable Glock 18" = true
	"Disable MP-443" = true
	"Disable M1911" = true
	"Disable Homemade Shotgun" = true
	"Disable Trachelium" = true
	"Disable MP5" = true
	"Disable Vector" = true
	"Disable AK-47" = true
	"Disable AK-12" = true
	"Disable SKS" = true
	"Disable M4A1" = true
	"Disable HK416" = true
	"Disable QBZ-95" = true
	"Disable QBZ-191" = true
	"Disable Insidious" = true
	"Disable MK14 EBR" = true
	"Disable QL-1031" = true
	"Disable Marlin 1894" = true
	"Disable Kar98k" = true
	"Disable Mosin-Nagant" = true
	"Disable SVD" = true
	"Disable AWM" = true
	"Disable M98B" = true
	"Disable Sentinel" = true
	"Disable Hunting Rifle" = true
	"Disable NTW-20" = true
	"Disable M870" = true
	"Disable AA-12" = true
	"Disable Devotion" = true
	"Disable RPK" = true
	"Disable M60" = true
	"Disable M2HB" = true
	"Disable Minigun" = true
	"Disable M79" = true
	"Disable Secondary Cataclysm" = true
	"Disable RPG-7" = true
	"Disable Javelin" = true
	"Disable 9K38 Igla" = true
	"Disable Bocek" = true
	"Disable Super Star Shooter" = true
	"Disable Vehicle Gun (internal)" = false
